using Geode.Core.Geometry;
using System;
using System.Collections.Generic;

namespace Geode.Core.Tessellation
{
    /// <summary>
    /// Optional vertex attributes that may be generated by <see cref="GeographicGridEllipsoidTessellator"/>.
    /// <see cref="Position"/> is always required; <see cref="Normal"/> and
    /// <see cref="TextureCoordinate"/> are produced on demand.
    /// </summary>
    [Flags]
    public enum GeographicGridEllipsoidVertexAttributes
    {
        Position = 1,
        Normal = 2,
        TextureCoordinate = 4,
        All = Position | Normal | TextureCoordinate
    }

    /// <summary>
    /// Tessellates an ellipsoid using a geographic (lat/lon) grid -- the same conceptual
    /// grid formed by the parallels and meridians of a globe.
    ///
    /// Vertices are arranged in horizontal "stacks" (rings of constant latitude) and
    /// vertical "slices" (meridians of constant longitude). Two singular pole vertices
    /// cap the top and bottom. The output mesh is a closed triangle list with
    /// counter-clockwise (outward-facing) winding.
    ///
    /// This scheme is simple and intuitive but not isotropic: triangles bunch up and
    /// become long-and-thin near the poles while triangles near the equator are nearly
    /// equilateral. For uniform triangle quality across the surface, prefer a recursive
    /// subdivision scheme (e.g. icosahedral / geodesic subdivision).
    /// </summary>
    public static class GeographicGridEllipsoidTessellator
    {
        /// <summary>
        /// Builds a triangle mesh approximating the surface of <paramref name="ellipsoid"/>.
        /// </summary>
        /// <param name="ellipsoid">The ellipsoid whose surface should be tessellated.</param>
        /// <param name="numberOfSlicePartitions">Number of longitudinal divisions (meridians). Minimum 3.</param>
        /// <param name="numberOfStackPartitions">Number of latitudinal divisions (parallels). Minimum 2.</param>
        /// <param name="vertexAttribFlags">Which vertex attributes to generate. Position is mandatory.</param>
        /// <returns>A <see cref="Mesh"/> with positions (and optionally normals / texture coordinates),
        /// indexed as a triangle list with counter-clockwise outward winding.</returns>
        public static Mesh Compute(Ellipsoid ellipsoid, int numberOfSlicePartitions, int numberOfStackPartitions, GeographicGridEllipsoidVertexAttributes vertexAttribFlags)
        {
            if(numberOfSlicePartitions < 3)
            {
                throw new ArgumentOutOfRangeException(nameof(numberOfSlicePartitions), "Must be at least 3.");
            }

            if(numberOfStackPartitions < 2)
            {
                throw new ArgumentOutOfRangeException(nameof(numberOfStackPartitions), "Must be at least 2.");
            }

            if((vertexAttribFlags & GeographicGridEllipsoidVertexAttributes.Position) != GeographicGridEllipsoidVertexAttributes.Position)
            {
                throw new ArgumentException("Position attribute is required.", nameof(vertexAttribFlags));
            }

            Mesh mesh = new Mesh()
            {
                    PrimitiveType = PrimitiveType.Triangles,
                    FrontFaceWindingOrder = WindingOrder.CounterClockwise
            };

            int numberOfVertices = NumberOfVertices(numberOfSlicePartitions, numberOfStackPartitions);
            var positionsAttribute = new VertexAttributeDoubleVector3("position", numberOfVertices);
            mesh.Attributes.Add(positionsAttribute);

            IndicesUnsignedInt indices = new IndicesUnsignedInt(3 * NumberOfTriangles(numberOfSlicePartitions, numberOfStackPartitions));
            mesh.Indices = indices;

            IList<Vector3H>? normals = null;
            if((vertexAttribFlags & GeographicGridEllipsoidVertexAttributes.Normal) == GeographicGridEllipsoidVertexAttributes.Normal)
            {
                VertexAttributeHalfFloatVector3 normalsAttribute = new VertexAttributeHalfFloatVector3("normal", numberOfVertices);
                mesh.Attributes.Add(normalsAttribute);
                normals = normalsAttribute.Values;
            }

            IList<Vector2H>? textureCoordinates = null;
            if ((vertexAttribFlags & GeographicGridEllipsoidVertexAttributes.TextureCoordinate) == GeographicGridEllipsoidVertexAttributes.TextureCoordinate)
            {
                VertexAttributeHalfFloatVector2 textureCoordinateAttribute = new VertexAttributeHalfFloatVector2("textureCoordinate", numberOfVertices);
                mesh.Attributes.Add(textureCoordinateAttribute);
                textureCoordinates = textureCoordinateAttribute.Values;
            }

            // -----------------------------------------------------------------
            // Vertex generation
            //
            // We parameterize the ellipsoid surface with two angles:
            //   theta -- longitude, swept around the Z axis in the XY plane (0..2π)
            //   phi   -- colatitude, measured from the +Z axis down to -Z   (0..π)
            //
            // For a unit sphere   p(theta, phi) = (sinφ cosθ, sinφ sinθ, cosφ).
            // For an ellipsoid we scale each component by its axis radius:
            //                     p = (Rx sinφ cosθ, Ry sinφ sinθ, Rz cosφ).
            //
            // sinθ and cosθ depend only on the slice column j, so we compute
            // them once and reuse them for every ring.
            // -----------------------------------------------------------------
            double[] cosTheta = new double[numberOfSlicePartitions];
            double[] sinTheta = new double[numberOfSlicePartitions];

            for (int j = 0; j < numberOfSlicePartitions; j++)
            {
                double theta = Trigonometry.TwoPi * ((double)j / numberOfSlicePartitions);
                cosTheta[j] = Math.Cos(theta);
                sinTheta[j] = Math.Sin(theta);
            }

            // Vertex buffer layout:
            //   [0]                 -- north pole (single vertex at phi = 0)
            //   [1     .. S]        -- ring 1                   (S = numberOfSlicePartitions)
            //   [S+1   .. 2S]       -- ring 2
            //   ...
            //   [last]              -- south pole (single vertex at phi = π)
            // Each interior ring is a closed loop of S vertices around the axis at constant phi.
            IList<Vector3D> positions = positionsAttribute.Values;
            positions.Add(new Vector3D(0, 0, ellipsoid.Radii.Z)); // north pole

            // i starts at 1 (not 0) so we skip the degenerate ring at phi = 0 where
            // every vertex would collapse onto the north pole. The loop ends at
            // stacks - 1 so we likewise skip the degenerate ring at phi = π. That
            // produces (stacks - 1) interior rings, matching NumberOfVertices.
            for(int i = 1; i < numberOfStackPartitions; i++)
            {
                double phi = Math.PI * ((double)i / numberOfStackPartitions);
                double sinPhi = Math.Sin(phi);

                // Pre-multiply sinφ by each axis radius so the inner loop only
                // needs two multiplies per vertex.
                double xSinPhi = ellipsoid.Radii.X * sinPhi;
                double ySinPhi = ellipsoid.Radii.Y * sinPhi;
                double zCosPhi = ellipsoid.Radii.Z * Math.Cos(phi);

                for(int j = 0; j < numberOfSlicePartitions; j++)
                {
                    positions.Add(new Vector3D(cosTheta[j] * xSinPhi, sinTheta[j] * ySinPhi, zCosPhi));
                }
            }
            positions.Add(new Vector3D(0, 0, -ellipsoid.Radii.Z)); // south pole

            // Normals and texture coordinates are derived from the geodetic surface
            // normal at each position. On a sphere this is just the normalized
            // position vector; on a true (oblate) ellipsoid the geodetic normal is
            // *not* parallel to the position vector, and Ellipsoid.GeodeticSurfaceNormal
            // accounts for that. Texture coordinates fall directly out of the normal
            // via an equirectangular (lat/lon -> uv) projection.
            if((normals != null) || (textureCoordinates != null))
            {
                for(int i = 0; i < positions.Count; i++)
                {
                    Vector3D geodeticSurfaceNormal = ellipsoid.GeodeticSurfaceNormal(positions[i]);

                    if (normals != null)
                    {
                        normals.Add(geodeticSurfaceNormal.ToVector3H());
                    }

                    if (textureCoordinates != null)
                    {
                        textureCoordinates.Add(SubdivisionUtility.ComputeTextureCoordinate(geodeticSurfaceNormal));
                    }

                }
            }

            // -----------------------------------------------------------------
            // Index generation
            //
            // The mesh has three regions:
            //   1. A triangle fan at the north pole connecting [0] to ring 1.
            //   2. A grid of quads (each split into two triangles) connecting
            //      every pair of adjacent rings.
            //   3. A triangle fan at the south pole connecting the last ring
            //      back down to the bottom vertex.
            //
            // Throughout: winding is counter-clockwise when viewed from *outside*
            // the ellipsoid, so the front face is the outward-facing one.
            // -----------------------------------------------------------------

            // --- Region 1: north-pole fan ------------------------------------
            // Ring 1 occupies indices 1..S. Each triangle is (pole, j, j+1).
            // The final triangle wraps index S back to index 1 to close the loop.
            for(int j = 1; j < numberOfSlicePartitions; j++)
            {
                indices.AddTriangle(new TriangleIndicesUnsignedInt(0, j, j + 1));
            }
            indices.AddTriangle(new TriangleIndicesUnsignedInt(0, numberOfSlicePartitions, 1)); // closing seam

            // --- Region 2: middle quad strips --------------------------------
            // For each pair of adjacent rings we walk around all S columns and
            // emit two triangles per column, forming a quad between them:
            //
            //      TL -------- TR        TL = topRowOffset    + j
            //       | \         |        TR = topRowOffset    + j + 1
            //       |   \       |        BL = bottomRowOffset + j
            //       |     \     |        BR = bottomRowOffset + j + 1
            //       |       \   |
            //       |         \ |
            //      BL -------- BR
            //
            // Splitting the quad along the BL->TR diagonal and winding CCW
            // (viewed from outside) gives:
            //
            //   tri 1: BL -> BR -> TR
            //   tri 2: BL -> TR -> TL
            //
            // The last column wraps: when j = S-1, TR/BR live in column 0 of
            // each row, so the seam quad is emitted explicitly after the loop.
            //
            // We process numberOfStackPartitions - 2 strips because the very
            // top and very bottom rings are stitched to the poles by the fans
            // in regions 1 and 3 instead of by quads.
            for (int i = 0; i < numberOfStackPartitions - 2; ++i)
            {
                // +1 in both offsets skips past the north-pole vertex at index 0.
                int topRowOffset = (i * numberOfSlicePartitions) + 1;
                int bottomRowOffset = ((i + 1) * numberOfSlicePartitions) + 1;

                for (int j = 0; j < numberOfSlicePartitions - 1; ++j)
                {
                    // Quad split into two CCW triangles along the BL->TR diagonal.
                    indices.AddTriangle(new TriangleIndicesUnsignedInt(bottomRowOffset + j, bottomRowOffset + j + 1, topRowOffset + j + 1));
                    indices.AddTriangle(new TriangleIndicesUnsignedInt(bottomRowOffset + j, topRowOffset + j + 1, topRowOffset + j));
                }

                // Seam quad: column (S-1) connects back to column 0 of the same rings.
                indices.AddTriangle(new TriangleIndicesUnsignedInt(bottomRowOffset + numberOfSlicePartitions - 1, bottomRowOffset, topRowOffset));
                indices.AddTriangle(new TriangleIndicesUnsignedInt(bottomRowOffset + numberOfSlicePartitions - 1, topRowOffset, topRowOffset + numberOfSlicePartitions - 1));
            }

            // --- Region 3: south-pole fan ------------------------------------
            // Mirror of the north-pole fan. We iterate the last ring backwards
            // (j from lastPosition-1 downward) so that, viewed from below the
            // south pole looking up, the winding is still CCW outward.
            int lastPosition = positions.Count - 1;
            for (int j = lastPosition - 1; j > lastPosition - numberOfSlicePartitions; --j)
            {
                indices.AddTriangle(new TriangleIndicesUnsignedInt(lastPosition, j, j - 1));
            }
            // closing seam (mirror of the north-pole closing triangle)
            indices.AddTriangle(new TriangleIndicesUnsignedInt(lastPosition, lastPosition - numberOfSlicePartitions, lastPosition - 1));

            return mesh;
        }

        /// <summary>
        /// Triangle count for the geographic grid:
        ///   2 * S triangles for the north and south pole fans,
        ///   plus 2 triangles per quad * (stacks - 2) interior strips * S columns.
        /// </summary>
        private static int NumberOfTriangles(int numberOfSliceParitions, int numberOfStackPartitions)
        {
            int numberOfTriangles = 2 * numberOfSliceParitions; // top and bottom pole fans
            numberOfTriangles += 2 * ((numberOfStackPartitions - 2) * numberOfSliceParitions); // interior quad strips
            return numberOfTriangles;
        }

        /// <summary>
        /// Vertex count for the geographic grid:
        ///   2 pole vertices, plus (stacks - 1) interior rings of S vertices each.
        /// </summary>
        private static int NumberOfVertices(int numberOfSlicePartitions, int numberOfStackPartitions)
        {
            return 2 + ((numberOfStackPartitions - 1) * numberOfSlicePartitions);
        }
    }
}
